.Dd July 20, 2023
.Dt XGGEN 1
.Sh NAME
.Nm xggen
.Nd random gameoflife board generator
.Sh SYNOPSIS
.Nm
.Op Fl hv
.Op Fl c Ar columns
.Op Fl r Ar rows
.Op Fl p Ar alive_probability
.Sh DESCRIPTION
The
.Nm
utility lets you generate random boards that can be loaded from xgameoflife and gameoflife programs.
.Sh OPTIONS
.Bl -tag -width indent
.It Fl h
show usage
.It Fl c
set the number of generated columns
.It Fl r
set the number of generated rows
.It Fl p
set the probability of generating an alive cell
.It Fl v
display the program version
.El
.Sh EXAMPLES
.Bl -tag -width indent
.It generate a random 100x100 board
xggen -c 100 -r 100 -p 0.2 > random.xg
.It generate an empty 50x50 board
xggen -c 50 -r 50 -p 0 > empty.xg
.It generate a random board and load it into xgameoflife
xggen -p 0.1 | xgameoflife -l /dev/stdin
.El
.Sh SEE ALSO
.Xr xgameoflife 6
.Xr gameoflife 6
.Sh AUTHORS
.An alpheratz0 Aq Mt alpheratz99@protonmail.com
.Sh BUGS
https://github.com/alpheratz0/xgutils/issues
